apiVersion: v1
kind: ConfigMap
metadata:
  name: urbanmove-config
  namespace: urbanmove
data:
  ANALYTICS_URL: "http://analytics-service:4003"
  FLEET_URL: "http://fleet-service:4004"
  KAFKA_BROKERS: "kafka-0.kafka.urbanmove.svc.cluster.local:9092"
