apiVersion: v1
kind: Secret
metadata:
  name: urbanmove-secrets
  namespace: urbanmove
  annotations:
    description: "Staging secrets - in production, use External Secrets Operator to sync from AWS Secrets Manager"
type: Opaque
stringData:
  JWT_SECRET: "Hon4MGGZZJEPHlxlFdq4XGdvu1+JWkD8gtmWY12AWAM="
  POSTGRES_URL: "postgres://urbanmove_admin:kVg8mh0gA05HHDf7HFb0NZOq@urbanmove-staging-postgres.cn4eo2g8qzmj.eu-west-3.rds.amazonaws.com:5432/urbanmove?sslmode=require&uselibpqcompat=true"
  TIMESCALEDB_URL: "postgres://urbanmove_admin:kVg8mh0gA05HHDf7HFb0NZOq@urbanmove-staging-postgres.cn4eo2g8qzmj.eu-west-3.rds.amazonaws.com:5432/urbanmove?sslmode=require&uselibpqcompat=true"
  REDIS_URL: "rediss://:twCXfRpC2tE2O3KbTT3GD33s@master.urbanmove-staging-redis.xrsuuc.euw3.cache.amazonaws.com:6379"
