apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: urbanmove

resources:
  - namespace.yaml
  - configmap.yaml
  - prometheus-config.yaml
  - external-secrets.yaml
  - auth-service.yaml
  - ingestion-service.yaml
  - analytics-service.yaml
  - fleet-service.yaml
  - user-api.yaml
  - web-dashboard.yaml
  - api-gateway.yaml
  - kafka.yaml
  - monitoring.yaml
  - elk.yaml

commonLabels:
  app.kubernetes.io/part-of: urbanmove
