apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: urbanmove
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service
  namespace: urbanmove
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: urbanmove
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-service
  namespace: urbanmove
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  namespace: urbanmove
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dashboard
  namespace: urbanmove
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: urbanmove
spec:
  replicas: 1
