global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files: ["alerts.yml"]
scrape_configs:
  - job_name: prometheus
    static_configs: [{targets: ["localhost:9090"]}]
  - job_name: auth-service
    static_configs: [{targets: ["auth-service:4001"]}]
  - job_name: ingestion-service
    static_configs: [{targets: ["ingestion-service:4002"]}]
  - job_name: analytics-service
    static_configs: [{targets: ["analytics-service:4003"]}]
  - job_name: fleet-service
    static_configs: [{targets: ["fleet-service:4004"]}]
  - job_name: user-api
    static_configs: [{targets: ["user-api:4005"]}]
  - job_name: web-dashboard
    static_configs: [{targets: ["web-dashboard:3000"]}]
  - job_name: api-gateway
    metrics_path: /stub_status
    static_configs: [{targets: ["api-gateway:80"]}]
